mpc:
  N: 60
  dt: 0.1
  nx: 4
  nu: 2
  w_pos: 1.0
  w_vel: 0.5
  w_acc: 1.0
  w_stl: 1.0
  exp_q1: 5.5 # exponential barrier
  exp_q2: 2.75

iteration:
  max_iter: 500
  init_lamb: 20
  lamb_decay: 0.7 # original: 0.7
  lamb_amplify: 2.0
  max_lamb: 10000.0
  alpha_options: [1., 0.5, 0.25, 0.125, 0.0625, 0.03125, 0.015625 , 0.0078125]
  tol: 0.0005

vehicle:
  wheelbase: 2.94
  width: 1.6
  length: 3.5
  velo_max: 10.0
  velo_min: 0.0
  yaw_lim: 3.14
  a_max: 2.0
  a_min: -2.0
  stl_lim: 1.57

initial_condition:
  state: [0., 0., 5.0, 0.]

obstacle:
  init_state: [5.0, 1.2, 3.0, 0.]
  action_gt: [0., 0.] # constant velocity, no steering
  wheelbase: 2.7
  width: 1.5
  length: 3.2
  d_safe: 1.0 # safety buffer

reference_trajectory:
  longit_ref: [0, 40.0]
  lateral_ref: [0, 0.]
  velo_ref: 6.0
  yaw_ref: 0.0
  num_wpts: 1000